---

#vhost related
- name: Create directory for vhosting link 
  file: path={{ vhost_src_dir }} state=directory

- name: Create directory for sites-enabled
  file: path={{ vhost_link_dir }} state=directory
  tags:
    - vhost_dir

- name: Create directory for vhost1
  file: path={{ vhost1_html_dir }} state=directory

- name: Create log directory for vhost1
  file: path={{ vhost1_log_dir }} state=directory

- name: Template vhost directory copy to /etc/nginx/sites-available/
  template: 
    src=templates/vhost1_nginx.conf.j2 
    dest={{ vhost_src_dir}}/vhost1_nginx.conf

- name: Copy vhost_index.html to {{ vhost1_html_dir }}
  copy:
    src=files/{{ vhost1_index_html }}
    dest={{ vhost1_html_dir }}/index.html

- name: Link /etc/nginx/sites-available/ to /etc/nginx/sites-enabled
  file: > 
    dest={{ vhost_link_dir}}/vhost1_nginx.conf
    src={{ vhost_src_dir}}/vhost1_nginx.conf
    state=link
  notify: restart nginx
